CREATE TABLE IF NOT EXISTS news (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    school_id VARCHAR(36) NULL,
    title VARCHAR(512) NOT NULL,
    content TEXT NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
);

---###---

DROP TABLE IF EXISTS news;